apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev1role
  namespace: dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list